# Generated by Django 4.2.1 on 2025-05-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_schedule_schedule_unique_room_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
