# Generated by Django 4.2.1 on 2025-05-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
