# Generated by Django 4.2.1 on 2025-06-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_teacher_city_teacher_country_teacher_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
