# Generated by Django 4.2.1 on 2025-06-23 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0018_alter_student_first_name_alter_student_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#3498db', 'Blue - Academic'), ('#e74c3c', 'Red - Examinations'), ('#2ecc71', 'Green - Holidays'), ('#f1c40f', 'Yellow - Meetings'), ('#9b59b6', 'Purple - Sports'), ('#e67e22', 'Orange - Cultural'), ('#34495e', 'Dark Gray - General')], default='#34495e', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('academic', 'Academic'), ('exam', 'Examination'), ('holiday', 'Holiday'), ('meeting', 'Meeting'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='is_all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
