# Generated by Django 4.2.1 on 2025-06-24 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_saturday_to_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='examination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='accounts.examination'),
        ),
    ]
