# Generated by Django 4.2.1 on 2025-06-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('general', 'General'), ('events', 'Events')], default='academic', max_length=20),
        ),
    ]
