# Generated by Django 4.2.1 on 2025-07-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_payment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['transaction_id'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
