# Generated by Django 4.2.7 on 2025-07-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_payment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
